raspberrypi/pico-examples

- adc/CMakeLists.txt
- adc/dma_capture/CMakeLists.txt
- adc/dma_capture/dma_capture.c
- adc/dma_capture/resistor_dac.pio
We didn't have any examples of hooking up DMA to ADC, and the setup on the ADC side is nonobvious.
See https://github.com/raspberrypi/pico-feedback/issues/1
> Add ADC DMA example

- pio/CMakeLists.txt
- pio/clocked_input/CMakeLists.txt
- pio/clocked_input/clocked_input.c
- pio/clocked_input/clocked_input.pio
See https://github.com/raspberrypi/pico-feedback/issues/38
This adds fairly minimal example of using a PIO state machine to sample data on an external clock. It uses one of the hard SPIs to drive data into the SM with a couple of jumper wires. Once this is in, we can document it in the SDK book, as there's currently a big leap between the WS2812 example and the logic analyser example.
> Add pio_clocked_input example

- pio/logic_analyser/logic_analyser.c
This fixes the PIO + DMA logic analyser example to handle non-power-of-2 sample widths correctly, and also generally cleans it up, adds more commentary, and sets the DMA to high bus priority so you should be able to crank the width all the way up to 32 bits. See #29
> Fix logic analyser for non-power-of-2 sample widths, and clean and comment (closes #29)

- blink/blink.c
- picoboard/blinky/blinky.c
- pio/pwm/pwm.c
This help the example to run with upcoming board without code modification from user.
> change blink to use PICO_DEFAULT_LED_PIN to support other boards

- pio/spi/spi_flash.c
- spi/bme280_spi/bme280_spi.c
- spi/mpu9250_spi/mpu9250_spi.c
- spi/spi_dma/spi_dma.c
- spi/spi_flash/spi_flash.c
This follows on from https://github.com/raspberrypi/pico-sdk/pull/225
I haven't actually tested any of these examples, but I have double-checked the changes I've made. I didn't use PICO_DEFAULT_SPI for `spi/mpu9250_spi` because that would also involve updating the [wiring diagram](https://github.com/raspberrypi/pico-examples/tree/master/spi/mpu9250_spi) which I don't have time to do right now.
> Update some of the SPI examples to use PICO_DEFAULT_SPI and binary_info

- usb/device/dev_lowlevel/dev_lowlevel.c
This makes it so a ZLP is sent as a response to OUT control requests other than SET_ADDRESS and SET_CONFIGURATION. Without it, other OUT control requests may crash communications.
I've experienced it on Windows 10 using the WinUSB driver / libusb library - after a custom control request, all transfer attempts would return LIBUSB_ERROR_ACCESS. This fixed it.
> usb/device/dev_low_level: respond to other OUT control requests with a ZLP

- i2c/bus_scan/bus_scan.c
When calling ```i2c_read_blocking```, use ```i2c_default``` rather than ```i2c0```.
> bus_scan: use i2c_default rather than i2c0

- pio/differential_manchester/differential_manchester.pio
The initial bit transition would be set even if the queue stalled.
The state machine still takes 16 cycles per bit
The next bit starts on state 1 and 9 instead of 0 and 8 so the timing is the same as before
> Prevent extra bit transition at end of data

- pio/pio_blink/blink.c
Added missing parenthesis around the divisor. Verified using a logic analyzer and also in simulation:
https://wokwi.com/arduino/projects/300911723685085709
> Fix pio_blink frequency calculation

- i2c/bus_scan/bus_scan.c
The comment in the code is incorrect. I tested this out, and it doesn't detect the device via those pins.
I was searching and found this comment thread: https://www.raspberrypi.org/forums/viewtopic.php?p=1822258&sid=1ff96911779abcedda7b3ae535d1d0af#p1822258
Sure enough, when I switched to pins 6 and 7, the code worked fine and could detect the device I had plugged into the i2c bus.
```
I2C Bus Scan
0  1  2  3  4  5  6  7  8  9  A  B  C  D  E  F
00 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
10 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
20 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
30 .  .  .  .  .  .  .  .  .  .  .  .  @  .  .  .
40 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
50 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  .
60 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .  . …
```
> bus_scan.c example - fix pin number in comment

- pio/ir_nec/README.adoc
The "List of Files" now links (only) to files, not to directories (which prevented this example being included in the C SDK databook)
> Update pio/ir_nec/README.adoc file links

- pio/quadrature_encoder/quadrature_encoder.pio
- Enable internal pull up on B-phase pin too.
- pio_gpio_init is not needed for input.
> PIO Quadrature fixes

- spi/spi_dma/spi_dma.c
In spi_dma.c, there was a typo in one comment and one confusing dash that could have been mistaken for a "minus sign"
> Fix typo in one comment in spi_dma example

- pio/pio_blink/blink.c
Works fine currently for low frequency, breaks down at higher frequency e.g. 1MHz
Chased down with a scope to the 3 extra cycles needed for wait+1; `mov`; `jmp` so account for these in demo program. When running now at 1MHz get the right 1µs delay on a scope.
> Fix PIO count

- rtc/hello_rtc/hello_rtc.c
A delay is needed after `rtc_set_datetime()` before the newly set value can be read back.
> Add delay to hello_rtc (#109)

- spi/spi_master_slave/README.adoc
The "List of Files" section should only list text-files (i.e. source code), not images or supplementary files
> Update spi_master_slave README

- README.md
> fix links to pico_w examples

- pico_w/tcp_server/picow_tcp_server.c
> Fix missing TCP_PORT for printf in TCP server example

- pico_w/access_point/dhcpserver/dhcpserver.c
- pico_w/access_point/picow_access_point.c
- pico_w/freertos/ping/picow_freertos_ping.c
- pico_w/ntp_client/picow_ntp_client.c
Fixes https://github.com/raspberrypi/pico-examples/issues/265
> Fix issues building examples with LWIP_IPV6

- usb/device/dev_lowlevel/dev_lowlevel.c
The usb/device/dev_lowlevel example does not work on macOS, showing a device enumeration error. The error occurs because more data is being sent than was requested.
> fixed issue with macOS for usb device dev_lowlevel example

- pico_w/freertos/ping/lwipopts.h
Now LWIP_PLATFORM_ASSERT works it asserts for the ping example app. It sets the SO_RCVTIMEO socket option which is not implemented.
Fixes #308
> ping example app throws lwip assert

- pio/ws2812/ws2812_parallel.c
Summary of changes:
* For clarity, avoid overloading term `string` ... use `strand` instead
* type: `string_t` --> `pixel_strand_t`
* variable name: `current_string_out` --> `current_strand_out`
* variable name: `current_string_4color` --> `current_strand_4color`
* variable name: `num_strings` --> `num_strands`
* etc.
* In function `pattern_fade()`
* Mark variable `level` as `const` and move into this function's scope
* Explicitly initialize static variable `error` to zero for clarity
> PIO WS2812 Sample: Change 'string' to 'strip'

- pico_w/freertos/iperf/picow_freertos_iperf.c
- pico_w/freertos/ping/picow_freertos_ping.c
The Pico W ping and iperf examples define [RUN_FREERTOS_ON_CORE](https://github.com/raspberrypi/pico-examples/blob/sdk-1.4.0/pico_w/freertos/ping/picow_freertos_ping.c#L20) but later refer to [RUN_FREE_RTOS_ON_CORE](https://github.com/raspberrypi/pico-examples/blob/sdk-1.4.0/pico_w/freertos/ping/picow_freertos_ping.c#L81). This PR fixes those typos.
> fix typos in pico-w examples

- usb/device/dev_lowlevel/dev_lowlevel.h
Comment location was misleading, intellisense associate the comment to 
the typedef type instead of struct usb_endpoint_configuration.
> Change comment location in dev_lowlevel

- pio/st7789_lcd/st7789_lcd.c
This fixes the example for the ST7789 displays that have the height of 320
> Generalize ST7789 init. sequence

- pico_w/access_point/dhcpserver/dhcpserver.c
See https://github.com/hathach/tinyusb/pull/1712 and the initial trigger https://github.com/OpenLightingProject/rp2040-dmxsun/issues/53:
The included DHCP server fails to process DHCP DISCOVER or REQUEST packages that don't contain the "DHCP MESSAGE TYPE" option as the first option in the package.
The initial report that triggered me was in https://github.com/OpenLightingProject/rp2040-dmxsun/issues/53 and after some investigation, I found that the "dhcpcd" client (maybe others, too) don't send the MESSAGE TYPE as the first option (see Wireshark dump attached in the linked issue). This seems to be valid since the order of the options contained in the package shouldn't matter. However, tinyUSB's DHCP server expects the MESSAGE TYPE to be the first option.
This change uses the already …
> Pico-W Access Point: Fix DHCP server for certain clients (dhcpcd)

- i2c/mpu6050_i2c/mpu6050_i2c.c
To reset the MPU6050, the device_reset bit shall be set to '1'.
reference from "MPU-6000/MPU-6050 Register Map and Descriptions"
DEVICE_RESET : When set to 1, this bit resets all internal registers to their default values. The bit automatically clears to 0 once the reset is done.
> Update on reset of mpu6050_i2c.c

- usb/device/dev_hid_composite/CMakeLists.txt
- usb/device/dev_hid_composite/usb_descriptors.c
Simple change to use the flash chip ID as the USB serial number with the TinyUSB example. I can squash/rebase as needed.
> Use the flash chip ID as the USB serial number

- pico_w/wifi/access_point/picow_access_point.c
- pico_w/wifi/iperf/picow_iperf.c
If the user presses "d" wifi is disconnected and the example exits. Tests new "disable" functions.
Fixes #386
> Call disable function for STA/AP modes.

- pio/quadrature_encoder/quadrature_encoder.c
- pio/quadrature_encoder/quadrature_encoder.pio
This is just an improvement over the previous version, where the PIO code now uses "just" 24 instructions instead of 29. Although it may seem a small difference, that leaves 8 instruction slots for other PIO code to run instead of just 3.
> quadrature encoder: reduce PIO code size from 29 to 24

- pico_w/bt/standalone/client.c
- pico_w/bt/standalone/server.c
- pico_w/bt/standalone/server_with_wifi.c
Add some comments about how btstack_run_loop_execute does nothing in threadsafe backrgound mode.
> Comments about btstack_run_loop_execute

- README.md
- pico_w/wifi/tls_client/CMakeLists.txt
- pico_w/wifi/tls_client/mbedtls_config.h
- pico_w/wifi/tls_client/picow_tls_client.c
- pico_w/wifi/tls_client/tls_common.c
- pico_w/wifi/tls_client/tls_verify.c
TLS should really be used with verification enabled, as otherwise you can still suffer from a "man in the middle" attack. Add an example that demonstrates how to do this.
Fixes #337
> Add an example for how to enable TLS verification.

- adc/read_vsys/power_status.c
Inexplicably using the wrongly named constant. Should be PICO_VBUS_PIN.
This is used for Pico, Pico W uses CYW43_WL_GPIO_VBUS_PIN
> Fix PICO_VBUS_PIN

- pico_w/wifi/access_point/dhcpserver/dhcpserver.c
The DHCP server broadcasts messages. This are being sent via the default netif which might be completely the wrong network. We want to send messages to the netif we got the original message from.
Fixes #382
> The dhcp server should reply to the right netif

- i2c/bus_scan/bus_scan.c
* closes https://github.com/raspberrypi/pico-feedback/issues/34
> Update comment to match code output

- README.md
- pico_w/bt/README.md
> Add a README for bluetooth debugging

- pio/ws2812/ws2812.c
Fixes #451 
I have also changed the `IS_RGBW` to false because the example is using `urgb_u32` which does not include the `white` color.
> Include urgbw_u32 function and document rgb vs rgbw

- pio/ws2812/ws2812.pio
The WS2812 PIO example uses poor choices of T1, T2, and T3, leading to poor support for transmission frequencies other than 0.8 MHz. Specifically, the example PIO program, when run at a bit frequency of 0.8 MHz, is at the bounds of the tolerances specified in the [WS2812B datasheet](https://cdn-shop.adafruit.com/datasheets/WS2812B.pdf).
This PR improves the maximum bit frequency to 1.028 MHz while remaining within tolerance (a 28% improvement).
The WS2812B datasheet lists the following tolerances:
- T0H = `0.4 us +- 0.15 us` = `0.25 us .. 0.55 us`
- T1H = `0.8 us +- 0.15 us` = `0.65 us .. 0.95 us`
- T0L = `0.85 us +- 0.15 us` = `0.7 us .. 1 us`
- T1L = `0.45 us +- 0.15 us` = `0.3 us .. 0.6 us`
Note: This gives a minimum possible time-per-bit of 0.95 us, and a maximum possible time-per-bit …
> WS2812 example: Improve bandwidth tolerance

- pico_w/bt/config/FreeRTOSConfig.h
- pico_w/wifi/freertos/iperf/FreeRTOSConfig.h
- pico_w/wifi/freertos/ping/FreeRTOSConfig.h
Issues with the latest version of the FreeRTOS-Kernel
> Fix freertos compilation

- README.md
There is a prebuilt Pico W blink at https://datasheets.raspberrypi.com/soft/blink_picow.uf2 but I don't know if a rptl.io shortcut exists for it.
> Add the Pico W specific blink to the First Examples section

- usb/device/dev_lowlevel/dev_lowlevel.c
The USB dev_lowlevel example silently fails in C++ because `isr_usbctrl` is name-mangled and therefore not registered as an interrupt handler. This PR adds `extern "C"` to use C linkage for this function and allow compiling as C++.  
It is certainly not the prettiest, but it is necessary for correct behavior (with C++ linkage, none of the host's packets are responded to and the device is useless). The alternative to this is to manually specify `irq_set_exclusive_handler`, probably within `usb_device_init`. The pico-sdk advertises itself as C/C++, so C++ compatibility should be taken into consideration in its examples.
> Add extern "C" to isr_usbctrl in dev_lowlevel

- flash/ssi_dma/CMakeLists.txt
- flash/ssi_dma/flash_ssi_dma.c
**Description:**
This PR introduces interrupt handling in the flash_ssi_dma example to enhance the stability of flash operations on the Raspberry Pi Pico. 
Based on insights from Kevin Boone's article (https://kevinboone.me/picoflash.html) and flash.h notes on stable flash memory usage, the updated code now disables interrupts during flash operations. Preventing conflicts especially with USB operations that could otherwise cause the program to hang. 
**Changes made:**
Added save_and_disable_interrupts() and restore_interrupts() around the flash operation block to prevent execution interruptions during flash memory access.
> Enhance flash SSI DMA example with interrupt control for stable operations

- pico_w/wifi/iperf/picow_iperf.c
The example in here uses an async callback to avoid a race when using stdio_usb. But there's a fix available for this issue so simplify the example.
To test pass -DPICO_STDIO_USB=1 on the cmake command line.
Fixes #461
> Simplify example of stdio_set_chars_available_callback

- bootloaders/CMakeLists.txt
Currently, a pico-examples build without the mbedtls submodule checked out in the SDK will fail, as picotool throws
```
ERROR: Cannot sign/hash partition table with no mbedtls
```
when making `enc_bootloader`, due to being compiled without mbedtls
Solve this by skipping `enc_bootloader` when there is no `pico_mbedtls`
> Skip encrypted bootloader with no mbedtls

- sha/mbedtls_sha256/mbedtls_sha256.c
- sha/sha256/hello_sha256.c
See https://github.com/raspberrypi/pico-examples/issues/520 and https://github.com/raspberrypi/pico-examples/commit/8953e1b75a5b4f3d28533e3e04f6767a465625f9
(and also https://github.com/raspberrypi/pico-sdk/pull/1863 )
> Workaround gcc/newlib issue on Ubuntu 24

- freertos/hello_freertos/hello_freertos.c
> Fix typo in macro definition

- bootloaders/encrypted/CMakeLists.txt
- bootloaders/encrypted/hello_serial.c
Removes the dependence on a file from a separate folder, which other examples don't have
This would allow the example to be used in the VS Code extension, as that needs examples to be contained in a single directory
> Copy hello_serial into bootloaders/encrypted

- pico_w/bt/picow_bt_example_common.c
- pico_w/bt/standalone/server_with_wifi.c
- pico_w/wifi/freertos/httpd/pico_freertos_httpd.c
- pico_w/wifi/freertos/iperf/picow_freertos_iperf.c
- pico_w/wifi/httpd/pico_httpd.c
- pico_w/wifi/iperf/picow_iperf.c
- pico_w/wifi/lwipopts_examples_common.h
- pico_w/wifi/tcp_server/picow_tcp_server.c
> Fix compile issues with LWIP_SINGLE_NETIF

- universal/CMakeLists.txt
If pictool_DIR is set then pass that, otherwise pass the picotool_INSTALL_DIR, which is only set when picotool is built as part of the SDK
Fixes #531 I think - although @lurch should probably double check
> Fix picotool_DIR and pioasm_DIR passing to universal build

- pio/quadrature_encoder/quadrature_encoder.c
- pio/quadrature_encoder/quadrature_encoder.pio
- pio/quadrature_encoder_substep/quadrature_encoder_substep.c
- pio/quadrature_encoder_substep/quadrature_encoder_substep.pio
Have to initialise the gpio function for rp2350.
Stop the quadrature_encoder example spamming sdio if nothing has changed.
Change the pins used for quadrature_encoder_substep so they match the other example.
Fixes #550
> Fix quadrature_encoder examples on rp2350

- otp/hello_otp/hello_otp.c
Check that the OTP rows being used for the hello_otp example are 0 before the example starts, else the example will throw other errors. This was prompted by #554, so it will now throw an error in that case explaining that the rows need to be changed.
> Check rows before running hello_otp example

- pio/hello_pio/hello.c
- pio/uart_rx/uart_rx.c
- pio/uart_rx/uart_rx_intr.c
- pio/uart_tx/uart_tx.c
- pio/uart_tx/uart_tx.pio
- pio/ws2812/ws2812.c
- pio/ws2812/ws2812_parallel.c
Fix some of the pio examples so they work properly if used with a pin >= 32.
> Fix some pio examples to work with gpios >= 32

- README.md
- i2c/slave_mem_i2c/CMakeLists.txt
- i2c/slave_mem_i2c/slave_mem_i2c_burst.c
uses i2c_write_burst_blocking and i2c_read_burst_blocking
> Add an example that uses burst APIs

- README.md
- pico_w/wifi/blink/CMakeLists.txt
- pico_w/wifi/blink/picow_blink_fast_clock.c
We have picow_blink_slow_clock, so we probably need an example of running it faster?
> Add a picow_blink_fast_clock example

- flash/program/flash_program.c
Although it's not required in this example, demonstrate how to call flash function using flash_safe_execute
Fixes #510
> Use flash_safe_execute

- pio/ws2812/ws2812.pio
```ws2812_parallel_program_init()``` contained an unneeded call to ```sm_config_set_set_pins()```. When this is called with the ```pin_count``` parameter set to a value larger than 7, the set pin count value in the pinctrl register overflows into the side-set pin count. This can result in hard to diagnose issues where low numbered GPIO pins don't work as expected.
There is an existing ```valid_params_if()``` check in ```sm_config_set_set_pins()``` which would catch this error but it is ignored in Release builds.
This PR just removes this ```sm_config_set_set_pins()``` call as **SET** commands aren't even used by the associated PIO code.
Discovered when trying to explain symptoms noted in [this forum thread](https://forums.raspberrypi.com/viewtopic.php?t=362071)
> WS2812: Support more than 7 pins in parallel mode

- pico_w/wifi/access_point/CMakeLists.txt
- pico_w/wifi/access_point/picow_access_point.c
> Use the function to set the IP address

- pio/squarewave/generated/squarewave.pio.h
- pio/squarewave/generated/squarewave_wrap.pio.h
- pio/ws2812/generated/ws2812.pio.h
The PIO version in no longer hard coded.
> Fix pio headers that are used in SDK docs

- README.md
- adc/read_vsys/power_status.h
- pico_w/bt/README.md
- pico_w/wifi/access_point/picow_access_point.c
Refer to Wifi / Bluetooth support instead.
> Remove some references to Pico W

- freertos/FreeRTOSConfig_examples_common.h
Current wording implied it would only be set for the RP2040 port code and the [RP2350 port](https://github.com/raspberrypi/FreeRTOS-Kernel/blob/main/portable/ThirdParty/GCC/RP2350_ARM_NTZ/library.cmake#L44) appears to have defined it on master.
> Updated FREE_RTOS_KERNEL_SMP comment to be applicable to any 2 core RP chip

- pico_w/wifi/mbedtls_config_examples_common.h
This PR enables NIST curve optimizations in shared mbedtls config, which significantly speed up TLS handshakes and communication by 4x to 8x. ([mbedtls docs](https://mbed-tls.readthedocs.io/projects/api/en/development/api/file/crypto__config_8h/#c.MBEDTLS_ECP_NIST_OPTIM))
[Issue#411](https://github.com/raspberrypi/pico-examples/issues/411#issuecomment-2607216547)
> Add NIST curves optimizations to shared mbedtls config

- i2c/lis3dh_i2c/lis3dh_i2c.c
TEMP_CFG_REG is 0x1F, not 0xC0. I suspect this is just a typo since the value written to it is 0xC0.
See https://www.mouser.com/datasheet/2/389/lis3dh-1849589.pdf#[{%22num%22%3A141%2C%22gen%22%3A0}%2C{%22name%22%3A%22XYZ%22}%2C61%2C439%2Cnull] .
> lis3dh_i2c: fix TEMP_CFG_REG address

- README.md
- usb/device/CMakeLists.txt
- usb/device/dev_cdc/CMakeLists.txt
- usb/device/dev_cdc/main.c
- usb/device/dev_cdc/tusb_config.h
- usb/device/dev_cdc/usb_descriptors.c
It demonstrates how to use TinyUSB with a CDC
interface while using the Pico SDK stdio USB.
> Added dev_cdc example

- pio/apa102/apa102.c
Simple typo correction which makes the red LED lights turn on as expected, following the wave pattern.
> Fix for issue #446: No red LED lights up in apa102.c example program.

- watchdog/hello_watchdog/hello_watchdog.c
Hello, 
I have changed the `hello_watchdog.c` example to detect only reboot caused by watchdog.
I have used the original example program and there was a wrong detection of watchdog caused reboot. For example, when a program was load on the RP2040 through uf2 file, then the RP2040 restart and the `result of watchdog_caused_reboot()` is `true`.
I have changed it to `watchdog_enable_caused_reboot()` cause based on the documentation found [here](https://www.raspberrypi.com/documentation/pico-sdk/hardware.html#ga455aa48ca6f11298e184d2ae0e81a085).
I have tested it on my own project, the detection was fine without detection of reboot caused by program upload, that is why i do a pull request to help others to use watchdog.
> Update hello_watchdog to detect reboot only by watchdog

- i2c/lis3dh_i2c/lis3dh_i2c.c
> LIS3DH is not a GPS

- pio/ws2812/ws2812_parallel.c
The data sheets for the ws2812 and ws2812b led strips (e.g., https://cdn-shop.adafruit.com/datasheets/WS2812.pdf) show that the required color order when sending data is GRB. The `put_pixel` function in `ws2812_parallel.c` inverts the order of the colors when putting data into a strip, so you end up with BRG, which means that your colors end up being weird or, at least, not what you expected.
Reversing the order of the additions to `current_strip_out` solves the problem.
> put_pixel in the parallel example sets the color order for the pixel to BRG instead GRB

- CMakeLists.txt
Corresponds to https://github.com/raspberrypi/pico-sdk/pull/2352 - should be merged before/when that is merged, else pico-examples will throw CMake warnings for using the example keys
> Allow example keys in the examples repo

- pico_w/wifi/tls_client/picow_tls_client.c
Change the TLS example to use our download server. worldtimeapi.org seems to be unreliable and it's a bit impolite to hit their server in our examples.
> Change TLS example URL

- pico_w/wifi/iperf/picow_iperf.c
- pico_w/wifi/ntp_client/picow_ntp_client.c
- pico_w/wifi/wifi_scan/picow_wifi_scan.c
Some general improvements to use async context
> Some example improvements

- pico_w/bt/standalone/server.c
> Add to standalone/sensor example to start/stop BT

- README.md
- bootloaders/CMakeLists.txt
- bootloaders/uart/CMakeLists.txt
- bootloaders/uart/uart-pt.json
- bootloaders/uart/uart_binary.c
- bootloaders/uart/uart_boot.c
Add a UART bootloader example, which reads a binary from the partition table on the main device, and uses the UART bootloader to boot that binary on a separate device. Requires a modified separate board to run, as you need access to the QSPI pins to use them as UARTs for the bootloader (see 5.8 in the datasheet) - the main board can be a normal RP2350 board.
This sample binary flashes the LED and prints "Hello, world" back over the UART interface, which demonstrates setting up QSPI GPIOs as UARTs.
> Add simple UART bootloader example

- pio/i2c/pio_i2c.c
This avoids a spurious shift on a write followed by a read. See discussion on #617
> PIO I2C example: clear ISR counter on each start/repstart
