raspberrypi/pico-examples

- ide/vscode/launch-raspberrypi-swd.json
- ide/vscode/launch-remote-openocd.json
> Fix the case of the 'gdbPath' setting, and locate the SVD using $PICO_SDK_PATH

- pio/ws2812/ws2812_parallel.c
> Fix #41 - Remove debug pin per @kilograham

- pio/ws2812/generated/ws2812.py
> generated python is changed

- usb/device/dev_hid_generic_inout/dev_hid_generic_inout.c
Seems like #30 got merged straight into `master`, without going via the usual `develop` -> `master` route?
This PR will hopefully fix things and make external rebases (like being done in #72) work a bit better :crossed_fingers:
> Cherry-pick #30 onto develop branch

- picoboard/blinky/blinky.c
> Fix condition for printing morse-code Z

- multicore/CMakeLists.txt
- spi/CMakeLists.txt
- system/CMakeLists.txt
A very quick PR that does what it says on the tin!
> Enforce alphabetical order in subdir CMakeLists

- blink/README.md
- blink/blink.c
I added comments to the blink.c script for beginners to get a better overview of the example script.
When I began with embedded system I would have liked that in my showcase examples, so I wanted to add that to the Raspberry Pi Pico example script.
The code without comments can be a bit intimidating for new users.
> added comments for clarification

- i2c/lis3dh_i2c/README.adoc
- i2c/mcp9808_i2c/README.adoc
- i2c/mma8451_i2c/README.adoc
- i2c/pa1010d_i2c/README.adoc
- i2c/pcf8523_i2c/README.adoc
Various fixes for odd formatting in the example README's
> Update README.adoc's for various examples to remove unnecessary block callouts.

- i2c/bmp280_i2c/bmp280_i2c.c
Confirmed as fixing the problem by reporter of the issue.
> Fixup a coding error in BME280 example

- pio/i2c/i2c.pio
- pio/i2c/pio_i2c.c
...instead of register bit manipulation
> Use PIO IRQ accessors in PIO I2C example

- clocks/hello_gpout/hello_gpout.c
> Fix incorrect gpio / gpout in hello_gpout

- README.md
- pico_w/CMakeLists.txt
Just keeps the README and pico-w/CMakeLists.txt comment consistent.
I saw the CMakeLists.txt file first and had a little trouble at first.
Thanks so much for the examples.
> README and comment change for pico-w example

- pico_w/CMakeLists.txt
> Load WIFI_SSID and WIFI_PASSWORD from environment

- i2c/ht16k33_i2c/ht16k33_i2c.c
> Fix debug build issue

- README.md
- pico_w/python_test_tcp/micropython_test_tcp_client.py
- pico_w/python_test_tcp/micropython_test_tcp_server.py
- pico_w/python_test_tcp/python_test_tcp_client.py
- pico_w/python_test_tcp/python_test_tcp_server.py
In Pico W TCP example test script was written in MicroPython. I needed to test on my desktop so I wrote tests in Python (not MicroPython) and think other people may need these test scripts.
> Add Python test scripts and rename MicroPython scripts

- pio/squarewave/CMakeLists.txt
- pio/ws2812/CMakeLists.txt
Add VERBATIM to add_custom_command
Fixes #297
> Fix build issues with spaces and parentheses

- pico_w/access_point/CMakeLists.txt
- pico_w/access_point/dhcpserver/dhcpserver.c
- pico_w/access_point/dnsserver/dnsserver.c
- pico_w/access_point/dnsserver/dnsserver.h
- pico_w/access_point/picow_access_point.c
Adds a DNS server and changes the AP example to use it
The AP example now serves a web page /ledtest that allows you to turn the led on and off.
> Improve ap example

- pico_w/bt/picow_bt_example_freertos.c
> Fix bt freertos build warnings

- pio/uart_rx/CMakeLists.txt
- pio/uart_rx/uart_rx_intr.c
Add PIO UART receive example which uses interrupts.
Fixes #377
> Example using a PIO interrupt

- pio/quadrature_encoder/quadrature_encoder.c
- pio/quadrature_encoder/quadrature_encoder.pio
as suggested on a previous pull, I'm fixing the indentation of the pio file to use spaces and assigning the copyright to Raspberry Pi. I don't mind giving up the copyright as long as the license keeps the code freely available for everyone to use, which the BSD 3 clause does
> coding style fixes, copyright waiver

- spi/bme280_spi/bme280_spi.c
> Fix bme280 example

- pico_w/bt/btstack_audio_pico.c
- pico_w/bt/hfp_hf_demo/CMakeLists.txt
- pico_w/bt/mod_player/CMakeLists.txt
- pico_w/bt/sine_player/CMakeLists.txt
When audio is initialised twice we get a error
> Fix bt audio examples

- pico_w/wifi/access_point/picow_access_point.c
> use LED_GPIO not 0

- i2c/ssd1306_i2c/img_to_array.py
when the last part of the image generate  in .h file it does not involve ";" at the end ,and will make error  when we start make the project
> fix error img_to_array.py

- pico_w/bt/README.md
Fixes https://github.com/raspberrypi/pico-sdk/issues/1457
> Add note to Bluetooth readme about link keys

- pico_w/wifi/access_point/picow_access_point.c
> Stop hard coding IP gateway and mask

- gpio/hello_gpio_irq/hello_gpio_irq.c
...which hopefully makes the code slightly more comprehensible
> Add a define for the pin number to hello_gpio_irq.c

- i2c/ssd1306_i2c/ssd1306_i2c.c
> SSD1306 example for bigger displays

- pico_w/wifi/ota_update/README.md
Still need to include something about Wifi "firmware" updates?
> Some updates
